<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_10</name>
   <tag></tag>
   <elementGuidId>702f9227-8f3b-4fdf-9483-3de5634cd609</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_mail_sidebar_needaction badge </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            10
        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client o_tooltip_parent o_no_chat_window&quot;]/div[@class=&quot;o_main&quot;]/div[@class=&quot;o_main_content&quot;]/div[@class=&quot;o_content&quot;]/div[@class=&quot;o_mail_chat&quot;]/div[@class=&quot;o_mail_chat_sidebar o_tooltip_parent&quot;]/div[@class=&quot;o_mail_chat_channel_item o_active&quot;]/span[@class=&quot;o_mail_sidebar_needaction badge&quot;]</value>
   </webElementProperties>
</WebElementEntity>
