<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_user-image</name>
   <tag></tag>
   <elementGuidId>b1e2fab4-c912-477c-afe8-381ce1d79982</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Username</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://photov31zoosk-a.akamaihd.net/00804964394231496587/s128.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zplusframe&quot;)/div[@class=&quot;frame-body-wrapper&quot;]/div[@class=&quot;frame-body-limited js-frame-body col-wrapper&quot;]/div[@class=&quot;col body-col&quot;]/div[@class=&quot;who-viewed-slideshow who-viewed-container content-container&quot;]/div[@class=&quot;mod-body&quot;]/div[@class=&quot;views-slideshow-container&quot;]/ul[@class=&quot;slideshow-list block-list&quot;]/li[@class=&quot;slideshow-view-tile view-tile media-unit&quot;]/figure[@class=&quot;photo-frame image-unit&quot;]/img[@class=&quot;user-image&quot;]</value>
   </webElementProperties>
</WebElementEntity>
