<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_o_project_kanban_main</name>
   <tag></tag>
   <elementGuidId>d9fd9715-bb32-4d82-b0c2-f57c80c17524</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o_project_kanban_main</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client o_tooltip_parent&quot;]/div[@class=&quot;o_main&quot;]/div[@class=&quot;o_main_content&quot;]/div[@class=&quot;o_content&quot;]/div[@class=&quot;o_view_manager_content&quot;]/div[@class=&quot;o_kanban_view oe_background_grey o_kanban_dashboard o_project_kanban o_kanban_ungrouped&quot;]/div[@class=&quot;oe_kanban_color_0 oe_kanban_global_click o_kanban_record&quot;]/div[@class=&quot;o_project_kanban_main&quot;]</value>
   </webElementProperties>
</WebElementEntity>
